[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xe43184267c00c4d421d4d0d274807c81afe0b160facf0c12c6fa3cdfe74ee764'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]